% 1) Estimate dark from the movie (skip first 300 frames)

a="E:\RZ\data\shi\260115_homo_cal590\test\fov2_-200_L_30lp\fov2_-200_L_30lp_1100nm_5x_00003_MC.tif";

darkOut = estimate_dark_from_movie(a, ...
                                   'MaxFrames', 1000, ...
                                   'Subsample', 4);

% 2) Apply per-pixel 3σ dark masking
outMask = apply_dark_mask_per_pixel(a, darkOut, ...
                                    'Factor', 3, ...          % 3 * sigma_dark
                                    'ClipNegative', true, ...
                                    'WriteTiff', true, ...
                                    'OutSuffix', '_minusDark');
